### ISSUE TITLE
which version of shell & makefile buildpack for deploy on heroku ?

### ISSUE THREAD

**Issue by todokku** [mauricioabreu/now-live#1]
Hi Mauricio ,
which version of shell & makefile buildpack for deploy on heroku ?
i only find this buildpack for heroku : https://github.com/dockhero/heroku-buildpack-docker-compose.git
please make deploy to heroku button for easy deploy to heroku 
waiting for your response
finest regards

**Comment by mauricioabreu** [comment]
Hi @todokku 
This project is still in development and should not be used in production.

Thank you for your interest!
